In [4]:
import math
import numpy as np

import pytpc
import pytpc.utilities as utils
import pytpc.simulation as sim

In [5]:
#calculating efield vector for NO tilt
#remember that B is always along detector (all in z)
emag = 9500
bmag = 1.68
tiltDegUVW = 0.0
tiltRadUVW = (tiltDegUVW*math.pi)/180
#print(tiltRad)

ef_orig = np.array([0, 0, emag])
bf_orig = np.array([0, 0, bmag])

trans = utils.tilt_matrix(tiltRadUVW)
ef = trans.dot(ef_orig)

print(ef)
print(bf_orig)

[    0.     0.  9500.]
[ 0.    0.    1.68]


In [6]:
#calculating drift velocity
vdmag = -5.2
tiltDegXYZ = 0.0
tiltRadXYZ = (tiltDegXYZ*math.pi)/180

vd = sim.drift_velocity_vector(vdmag, emag, bmag, tiltRadXYZ)
print(vd)

[-0.  -0.  -5.2]
